log_level: info

# -------------------------------------------------------------------
# Cross-Upstream Cache Settings
# -------------------------------------------------------------------
cache:
  # Global cache toggle. When disabled, *all* methods bypass cache.
  enabled: true

  # Cache settings for each method.
  methods:
    chainHead_v1_header:
      enabled: true
      max_entries: 100
    chainHead_v1_storage:
      enabled: true
      max_entries: 25
    chainHead_v1_body:
      enabled: true
      max_entries: 25
    chainHead_v1_call:
      enabled: true
      max_entries: 25

# -------------------------------------------------------------------
# IP rate limiting
# -------------------------------------------------------------------
rate_limit:
  enabled: false
  window: 1m
  max_requests: 100
  # Trusted networks for forwarding/proxy headers.
  # CIDR notation is used to specify the network ranges.
  trusted_networks:
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 127.0.0.1/32

# -------------------------------------------------------------------
# Upstream Servers Settings
# -------------------------------------------------------------------
upstream:
  servers:
    #- name: subway
    #  url: wss://polkadot-asset-hub-rpc.polkadot.io
    #  #url: ws://localhost:9945
    #  presets: polkadot_legacy
    - name: chaos
      url: ws://localhost:9944
    #  request_timeout: 5s
    #  connection_timeout: 10s
    #  max_connections: 100
    #  retry_delay: 1s
    - name: stakeworld
      url: wss://dot-rpc.stakeworld.io
      presets: polkadot
      methods:
        chainHead_v1_follow:
          max_subscribers: 4
    - name: helix
      url: wss://rpc-polkadot.helixstreet.io
      presets: polkadot
      methods:
        chainHead_v1_follow:
          max_subscribers: 4

# -------------------------------------------------------------------
# JSON-RPC Settings
# -------------------------------------------------------------------
json_rpc:
  max_pending_requests_per_connection: 150
  max_pending_requests: 500
  max_requests_per_second: 1500
