log_level: info

# Websocket connection per IP rate limit
rate_limit:
  enabled: false
  window: 1m
  max_requests: 100
  # Trusted networks for forwarding/proxy headers
  trusted_networks:
    - 192.168.0.0/16
    - 172.16.0.0/12
    - 127.0.0.1/32

# Upstream servers
upstream:
  debug:
    stats:
      enabled: false
      interval: 30s
  servers:
    - name: subway
      #url: wss://polkadot-rpc.publicnode.com
      url: ws://localhost:9945
      presets: polkadot_legacy
    #- name: chaos
    #  url: ws://localhost:9944
    #  request_timeout: 5s
    #  connection_timeout: 10s
    #  max_connections: 100
    #  retry_delay: 1s
    - name: stakeworld
      url: wss://dot-rpc.stakeworld.io
      presets: polkadot_v1
      methods:
        chainHead_v1_follow:
          max_subscribers: 4
    - name: helix
      url: wss://rpc-polkadot.helixstreet.io
      presets: polkadot_v1
      methods:
        chainHead_v1_follow:
          max_subscribers: 4
json_rpc:
  max_pending_requests_per_connection: 150
  max_pending_requests: 500
  max_requests_per_second: 150
